name: Next.js CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn 3.6.4
        run: corepack prepare yarn@3.6.4 --activate

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn lint

      - name: Run Type Check
        run: yarn type-check

      - name: Run Tests
        run: yarn test --passWithNoTests

      - name: Build Next.js
        run: yarn build